#!/usr/bin/env bash
# Writes docs/environment.md. Run this FIRST; every version claim in the
# README is filled from its output, never from memory.
set -uo pipefail
OUT=docs/environment.md
mkdir -p docs
{
  echo "# Environment (generated by scripts/probe-toolchain.sh)"
  echo; echo "Generated: $(date -u +%FT%TZ)"; echo
  echo '```'
  echo "uname          : $(uname -srm)"
  echo "python3        : $(python3 --version 2>&1)"
  echo "lldb           : $(lldb --version 2>&1 | head -1 || echo MISSING)"
  echo "lldb -P        : $(lldb -P 2>/dev/null || echo MISSING)"
  echo "clang          : $(clang --version 2>&1 | head -1 || echo MISSING)"
  echo "mlir-opt       : $(mlir-opt --version 2>&1 | head -2 | tr '\n' ' ' || echo 'NO MLIR')"
  echo "MLIR cmake     : $(find /usr /opt /usr/local -name MLIRConfig.cmake 2>/dev/null | head -1)"
  echo "cmake          : $(cmake --version 2>&1 | head -1 || echo MISSING)"
  P=$(lldb -P 2>/dev/null)
  if [ -n "$P" ]; then
    echo -n "import lldb    : "
    PYTHONPATH="$P" python3 -c 'import lldb;print("OK", lldb.__file__)' 2>&1 | head -1
  fi
  echo '```'
} > "$OUT"
cat "$OUT"