DTYPES = {"f32": "DT_F32", "f64": "DT_F64", "i32": "DT_I32", "i64": "DT_I64", "i8": "DT_I8"}

class Emitter:
    def __init__(self): self.lines = []; self.op_lines = {}; self.locals = {}; self.indent = 0; self.symbol = None
    def w(self, text=""): self.lines.append("    " * self.indent + text); return len(self.lines)
    def emit_op(self, op, text): n = self.w(text); self.op_lines[op.op_id] = n; return n

def emit(mod):
    e = Emitter()
    schema = next((o.attrs["name"] for o in mod.live if o.op_name == "toy_schema.schema_ref"), "Schema")
    e.symbol = f"{schema}_validate"
    e.w("// GENERATED by schemac. Do not edit."); e.w('#include "mlir_rt.h"'); e.w()
    e.w(f"bool {e.symbol}(SchemaObject* obj, RuntimeError* err) {{")
    e.indent += 1; e.w("bool __ok = true;")
    for op in mod.live:
        vid = op.results[0] if op.results else None
        lv = "__mlir_v" + vid.lstrip("%") if vid else None
        if vid: e.locals[vid] = lv
        n = op.op_name.rsplit(".", 1)[-1]
        if n == "schema_ref": e.emit_op(op, f"SchemaObject* {lv} = obj;")
        elif n == "field_ref": e.emit_op(op, f'SchemaField* {lv} = schema_field(obj, "{op.attrs["field_name"]}");')
        elif n == "validate_string":
            src = e.locals.get(op.operands[0], "obj")
            e.emit_op(op, f"bool {lv} = schema_validate_string({src}, {op.attrs['max_len']}, err);")
            e.w(f"__ok = __ok && {lv};")
        elif n == "validate_range":
            src = e.locals.get(op.operands[0], "obj")
            e.emit_op(op, f"bool {lv} = schema_validate_range({src}, {op.attrs['min']}LL, {op.attrs['max']}LL, err);")
            e.w(f"__ok = __ok && {lv};")
        elif n == "tensor_alloc":
            shape = list(op.attrs["shape"]) + [0] * (4 - len(op.attrs["shape"]))
            e.w(f"const int64_t {lv}_shape[4] = {{{', '.join(map(str, shape))}}};")
            e.emit_op(op, f"TensorView {lv} = tensor_alloc({DTYPES[op.attrs['dtype']]}, {len(op.attrs['shape'])}, {lv}_shape);")
        elif n == "dsp_alloc":
            a = op.attrs
            e.emit_op(op, f"DspBuffer {lv} = dsp_alloc({a['frames']}, {a['channels']}, {a['sample_rate']});")
    e.w("return __ok;"); e.indent -= 1; e.w("}")
    return e
